# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('stamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('stamp',),
            },
        ),
    ]
