# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
