# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20171006_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='heat_index',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
